version: '3'

services:
  postgres:
    image: postgres:11.3
    ports:
      - 127.12.1.1:5432:5432
    volumes:
      - postgres:/var/lib/postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      internal-network:
      heimdall-backend-global:
        aliases:
          - heimdall-backend-postgres

  nginx:
    build: .docker/nginx
    ports:
      - 127.12.1.1:80:80
    volumes:
       - ${PWD-.}:/app
    links:
      - php
    env_file:
      - .env
    networks:
      internal-network:
      heimdall-backend-global:
        aliases:
          - heimdall-backend-nginx

  php:
    build: .docker/php
    volumes:
      - ${PWD-.}:/app
    links:
      - postgres
    working_dir: /app
    env_file:
      - .env
    networks:
      internal-network:
      heimdall-backend-global:
        aliases:
          - heimdall-backend-php

volumes:
  postgres:

networks:
  internal-network:
  heimdall-backend-global:
    external: true
